version: '2'
services:
  web:
    build: .
    image: pierone.stups.zalan.do/mentoring/pazuzu-registry:1.1.1
    ports:
    - "8080:8080"
    links:
    - postgres-db
    environment:
    - 'SPRING_APPLICATION_JSON={"spring":{"profiles": {"active": "dev"}, "datasource":{"username": "postgres", "url": "jdbc:postgresql://postgres-db:5432/postgres"}}, "pazuzu": {"registry": {"admins": "jnarloch"}}}'
  postgres-db:
    image: registry.opensource.zalan.do/stups/postgres:9.4.5-1
    expose:
    - "5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: {}
