tokens:
  access-token-uri: https://token.services.auth.zalando.com/oauth2/access_token?realm=/services
  credentials-directory: /meta/credentials
  token-info-uri: https://info.services.auth.zalando.com/oauth2/tokeninfo
  token-configuration-list:
   - token-id: kio
     scopes:
      - uid

twintip:
  mapping: /api
  yaml: classpath:/api/swagger.yaml

spring:
  profiles:
    active: production
  datasource:
    url: jdbc:hsqldb:mem:pazuzudb;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

endpoints:
  enabled: false
  health:
    enabled: true
    path: /api/health

server:
  use-forward-headers: true

pazuzu:
  registry:
    admins: admin